### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ghost** [Lanceshi2/SyncFileYouWant#1]
Good plugin. Could you support "sync on save" or sync changed file only? many thanks

**Comment by Lanceshi2** [comment]
Thank you for the comments. But is there any particular scenario you want those features? 

For sync changed files only, I have considered this feature that if the file is not changed, then do nothing. But I do find some scenarios when the file on the destination folder is corrupted and you want to sync the file even if no change is made. 

For sync on save, well, as I mentioned in my readme file, although I want both folders to be synced, but I do find sometimes people want to keep some files identical - for experiment or for version purposes. If you do need a full sync, I recommend you using the filesync plugin which will automatically sync all the files between two folders. 

Thanks,
Lance

**Comment by ghost** [comment]
The first case is, I am editing a LESS file then I press "Ctrl+B" to compile it to .css and .map files. To sync these changes I have to open and  "ctrl + alt + s" on each files. That is very inconvenient.

In another case, I use SublimeSaveOnBuild to trigger LESS builder and it would better if SyncFileYouWant can detect files changed and sync them automatically.

**Comment by lance-shi** [comment]
Hi, sorry I don't quite look at that account quite often. To answer your question: 

1, You don't have to open each file. On the sidebar, choose multiple files and right click > Sync file. 
2, I don't do an automatic file sync because 
      a) this plugin is initially designed for FTR lab usage and we don't want to sync every file we change because of some certain scenarios.
      b) the automatic plugin of syncing files is already there: check https://sublime.wbond.net/packages/FileSync
