### ISSUE TITLE
Sync one folder to multiple destinations

### ISSUE THREAD

**Issue by migliori** [Lanceshi2/SyncFileYouWant#2]
Hi,

Great and very useful plugin, thanks.

I have to sync Sync one folder to 2 different destinations, and only first destination is detected.
Have you got a solution to achieve this ?

Thanks,

Gilles

**Comment by Lanceshi2** [comment]
Not at the moment. I will update the code and give a fix to it.

**Comment by Lanceshi2** [comment]
Feature added. Now you can put multiple destinations like: 
        {
            "source": "/Users/lanceshi/SyncFileYouWant",
            "dest": "/Users/lanceshi/developer/LanceTest",
        },
        {
            "source": "/Users/lanceshi/SyncFileYouWant",
            "dest": "/Users/lanceshi/developer/LanceTest2",
        }
And will sync to both folders

**Comment by migliori** [comment]
Wonderful !

It will be very usefull for me. Is there a way to send you a small donation to thank you ?

**Comment by Lanceshi2** [comment]
@migliori Thank you for the appreciation. Glad you like it. And no, you don't need to pay me anything for that. It is a pure freeware
